### ISSUE TITLE
Maps not loading on Samsung galaxy s3 and Huawei Honor 4C

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-cardboard#4]
I have implemented tangram maps in my app by simply adding a gradle build dependency 

`compile 'com.mapzen.tangram:tangram:0.1'
`
Now maps are loading fine on Google nexus 5 and Samsung galaxy s5 but it does not load on following devices:
Samsung galaxy s3, OS 4.3
Huawei Honor 4C, OS 4.4.2

Am i using the right gradle dependency or is there something wrong with my implementation. Because the same app/code is working fine(maps loading) on other two devices.?

**Comment by matteblair** [comment]
Are you trying to run the Google Cardboard demo that's in this repository, or just trying to make an Android app that uses tangram?

That is the correct dependency to add for a general-purpose Android application using tangram. If you're not trying to do something specifically with this Cardboard demo, please make an issue in here: https://github.com/tangrams/tangram-es with a specific description of what's going wrong on those two phones.
